[package]
name = "baanto"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_path_to_error = "0.1.16"
serde_repr = "0.1.19"
tokio = { version = "1.44.2", features = ["full"] }
